# Generated by Django 4.1.3 on 2022-11-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='本タイトル')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBNコード')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='本棚タイトル')),
                ('cat', models.PositiveIntegerField(choices=[(0, '指定なし'), (1, 'マンガ'), (2, '小説'), (3, '参考書'), (4, '実用書'), (5, '教科書'), (6, '雑誌')], default=0, verbose_name='カテゴリ')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='book',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bookshelf', verbose_name='紐づく本棚'),
        ),
    ]
