# Generated by Django 4.1.3 on 2022-11-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bookshelf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='cat',
            field=models.PositiveIntegerField(choices=[(0, '指定なし'), (1, 'マンガ'), (2, '文芸'), (3, '参考書'), (4, '実用書'), (5, '専門書'), (6, '雑誌'), (7, '絵本')], default=0, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(default='ログインしているアカウント', max_length=30, verbose_name='制作者'),
        ),
    ]
